services:
  db:
    image: postgres:15-alpine
    container_name: blog_db
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: main_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - blog_net

  backend:
    build: .
    container_name: blog_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/main_db
      SPRING_DATASOURCE_USERNAME: main_user
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - blog_net

networks:
  blog_net:
